env:
  CI_NAME: Nightly CI
jobs:
  build:
    if: ${{ github.repository == 'osfans/trime' && github.ref == 'refs/heads/develop'
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: cache-hash
      name: Calculate JNI cache hash
      run: './gradlew :app:calculateNativeCacheHash

        '
    - continue-on-error: true
      id: jni-cache
      name: Fetch JNI cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-trime-jni-release-${{ steps.cache-hash.outputs.native-cache-hash
          }}
        path: app/prebuilt
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - continue-on-error: true
      name: Setup keystore
      run: 'echo ${{ secrets.SIGNING_KEY }} | base64 --decode | cat >> $(pwd)/signingkey.jks

        cat << EOF > keystore.properties

        storeFile=$(pwd)/signingkey.jks

        storePassword=${{ secrets.KEY_STORE_PASSWORD }}

        keyAlias=${{ secrets.ALIAS }}

        keyPassword=${{ secrets.KEY_PASSWORD }}

        EOF

        '
    - continue-on-error: true
      name: Build Trime
      run: make release
    - continue-on-error: true
      if: ${{ !steps.jni-cache.outputs.cache-hit }}
      name: Add JNI cache
      run: cp -R app/build/intermediates/stripped_native_libs/release/out/lib app/prebuilt
    - continue-on-error: true
      name: Create Nightly release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: nightly
        files: 'app/build/outputs/apk/release/*.apk

          '
        prerelease: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: Nightly Build
name: Nightly
on:
  repository_dispatch:
    types: trigger-ga___nightly-ci.yml
