env:
  CI_NAME: Pull Request CI
jobs:
  build:
    env:
      BUILD_ABI: armeabi-v7a,arm64-v8a,x86,x86_64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: vars
      name: Get branch name
      run: 'echo ${GITHUB_REF#refs/*/}

        echo CI_BRANCH=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

        '
      shell: bash
    - continue-on-error: true
      if: startsWith(matrix.os, 'macos')
      name: Install macOS dependency
      run: 'brew install coreutils clang-format

        '
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: cache-hash
      name: Calculate JNI cache hash
      run: './gradlew :app:calculateNativeCacheHash

        '
    - continue-on-error: true
      id: jni-cache
      name: Fetch JNI cache
      uses: actions/cache@v4
      with:
        key: ${{ matrix.os }}-trime-jni-debug-${{ steps.cache-hash.outputs.native-cache-hash
          }}
        path: app/prebuilt
    - continue-on-error: true
      if: ${{ !steps.jni-cache.outputs.cache-hit }}
      name: Fetch submodules
      run: 'git submodule update --init --recursive

        '
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - continue-on-error: true
      if: ${{ !startsWith(matrix.os, 'windows') }}
      name: Check code style
      run: 'make style-lint

        '
    - continue-on-error: true
      name: Build debug Trime
      run: './gradlew :app:assembleDebug

        '
    - continue-on-error: true
      if: ${{ !steps.jni-cache.outputs.cache-hit }}
      name: Add JNI cache
      run: cp -R app/build/intermediates/stripped_native_libs/debug/out/lib app/prebuilt
      shell: bash
    - continue-on-error: true
      name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: trime-${{ matrix.os }}
        path: app/build/outputs/apk/debug/
        retention-days: 30
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - macos-13
        - macos-14
        - windows-2022
name: Pull Request
on:
  repository_dispatch:
    types: trigger-ga___pull-request-ci.yml
